// Bake assets/sfx/*.wav into src/sfx.js as base64 so the SFX work offline over
// file:// (no fetch), exactly like the embedded sprite art. Run after gen-sfx:
//   node scripts/gen-sfx.mjs && node scripts/embed-sfx.mjs
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sfxDir = path.join(projectDir, 'assets', 'sfx');
const outFile = path.join(projectDir, 'src', 'sfx.js');

if (!existsSync(sfxDir)) { console.error('no assets/sfx - run gen-sfx.mjs first'); process.exit(1); }

const files = readdirSync(sfxDir).filter(f => f.endsWith('.wav')).sort();
if (!files.length) { console.error('no .wav files in ' + sfxDir); process.exit(1); }

let total = 0;
const entries = files.map(f => {
  const buf = readFileSync(path.join(sfxDir, f));
  total += buf.length;
  const key = path.basename(f, '.wav');
  return '  ' + JSON.stringify(key) + ': "' + buf.toString('base64') + '"';
});

const body =
  '// =====================================================================\n' +
  '//  AUTO-GENERATED by scripts/embed-sfx.mjs - do not edit by hand.\n' +
  '//  Base64 WAV sound effects (generated by the sfxgen sister project via\n' +
  '//  scripts/gen-sfx.mjs). HC.Audio decodes these into AudioBuffers on init.\n' +
  '// =====================================================================\n' +
  'window.HC = window.HC || {};\n' +
  'HC.SFX = {\n' + entries.join(',\n') + '\n};\n';

writeFileSync(outFile, body);
console.log('embedded ' + files.length + ' sounds (' + Math.round(total / 1024) + 'KB wav -> ' +
  Math.round(body.length / 1024) + 'KB src/sfx.js)');
