// Embed every assets/sprites/*.png as a base64 data URI in src/art/sprites.js,
// so generated image sprites override the cute vector art while still running
// offline (no fetch). Re-run this whenever sprites are added/regenerated.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = 'assets/sprites';
const files = readdirSync(dir).filter((f) => f.endsWith('.png')).sort();
const entries = files.map((f) => {
  const key = f.replace(/\.png$/, '');
  const b64 = readFileSync(join(dir, f)).toString('base64');
  return '  ' + JSON.stringify(key) + ": 'data:image/png;base64," + b64 + "'";
});

const out =
  '// Generated raster image sprites (base64 PNGs), produced via Codex image_gen.\n' +
  '// AUTO-GENERATED by scripts/embed-sprites.mjs - do not edit by hand.\n' +
  '// Each entry overrides the matching texture key with a real image; any key NOT\n' +
  '// listed here falls back to the cute Canvas-2D art in cute.js / textures.js.\n' +
  '// Embedded as data URIs so the game still runs offline over file:// (no fetch).\n' +
  'window.HC = window.HC || {};\n' +
  'HC.SpriteImages = {\n' +
  entries.join(',\n') +
  '\n};\n';

writeFileSync('src/art/sprites.js', out);
console.log('embedded ' + entries.length + ' sprites (' + files.join(', ') + ') into src/art/sprites.js');
