// =====================================================================
//  Audio: plays sampled SFX (generated by the sfxgen sister project and
//  embedded as base64 WAV in src/sfx.js), decoded into AudioBuffers on the
//  first user gesture. Every cue falls back to a tiny built-in Web-Audio
//  synth blip if its sample hasn't decoded yet (or fails), so the game is
//  never silent. Must be unlocked by a user gesture (HC.Audio.init).
// =====================================================================
window.HC = window.HC || {};

HC.Audio = {
  ctx: null,
  master: null,
  muted: false,
  ok: true,
  sfxLevel: 0.83,       // global SFX gain multiplier (-17% vs music)
  buffers: null,        // key -> AudioBuffer (filled in as they decode)
  _sfxStarted: false,

  init: function () {
    if (!this.ok) return;
    if (!this.ctx) {
      try {
        var AC = window.AudioContext || window.webkitAudioContext;
        if (!AC) { this.ok = false; return; }
        this.ctx = new AC();
        this.master = this.ctx.createGain();
        this.master.gain.value = 0.5;
        this.master.connect(this.ctx.destination);
      } catch (e) { this.ok = false; return; }
    }
    if (this.ctx && this.ctx.state === 'suspended') this.ctx.resume();
    this._decodeSamples();
  },

  toggleMute: function () {
    this.muted = !this.muted;
    if (this.master) this.master.gain.value = this.muted ? 0 : 0.5;
    return this.muted;
  },

  // ---- sampled playback ----
  _decodeSamples: function () {
    if (this._sfxStarted || !this.ctx || !window.HC.SFX) return;
    this._sfxStarted = true;
    this.buffers = {};
    var self = this;
    Object.keys(window.HC.SFX).forEach(function (key) {
      try {
        var bin = atob(window.HC.SFX[key]);
        var bytes = new Uint8Array(bin.length);
        for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
        var done = function (buf) { if (buf) self.buffers[key] = buf; };
        var p = self.ctx.decodeAudioData(bytes.buffer, done, function () {});
        if (p && p.then) p.then(done, function () {});
      } catch (e) { /* leave it undecoded; the cue falls back to a synth blip */ }
    });
  },

  // Play a decoded sample; returns false if it isn't ready (so callers can
  // fall back to the synth). `rate` re-pitches, `vol` scales this one shot.
  play: function (key, rate, vol) {
    if (!this.ok || this.muted || !this.ctx) return false;
    var buf = this.buffers && this.buffers[key];
    if (!buf) return false;
    try {
      var src = this.ctx.createBufferSource();
      src.buffer = buf;
      if (rate) src.playbackRate.value = rate;
      var g = this.ctx.createGain();
      g.gain.value = (vol == null ? 1 : vol) * this.sfxLevel;
      src.connect(g); g.connect(this.master);
      src.start();
      return true;
    } catch (e) { return false; }
  },

  // ---- synth fallback (the original tiny blip) ----
  blip: function (freq, dur, type, vol, slideTo) {
    if (!this.ok || !this.ctx || this.muted) return;
    var t = this.ctx.currentTime;
    var osc = this.ctx.createOscillator();
    var g = this.ctx.createGain();
    osc.type = type || 'square';
    osc.frequency.setValueAtTime(freq, t);
    if (slideTo) osc.frequency.exponentialRampToValueAtTime(slideTo, t + dur);
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime((vol || 0.25) * this.sfxLevel, t + 0.01);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    osc.connect(g);
    g.connect(this.master);
    osc.start(t);
    osc.stop(t + dur + 0.02);
  },

  // ---- game cues (sample first, synth blip as a safety net) ----
  pickup:  function () { if (!this.play('pickup'))      this.blip(420, 0.10, 'square',   0.22, 720); },
  cookEnd: function () { if (!this.play('cook'))        this.blip(540, 0.12, 'triangle', 0.26, 880); },
  serve:   function () { if (!this.play('serve'))     { this.blip(660, 0.10, 'square', 0.26, 990);
                         var s = this; setTimeout(function () { s.blip(990, 0.14, 'square', 0.24, 1320); }, 90); } },
  combo:   function (n) { var rate = 1 + Math.min((n || 1) - 1, 8) * 0.06;
                          if (!this.play('combo', rate)) this.blip(700 + n * 80, 0.12, 'triangle', 0.26, 1100 + n * 90); },
  fail:    function () { if (!this.play('fail', 1, 0.9)) this.blip(300, 0.22, 'sawtooth', 0.24, 120); },
  deny:    function () { if (!this.play('deny', 1, 0.8)) this.blip(180, 0.08, 'square',   0.18, 140); },
  dash:    function () { if (!this.play('dash', 1, 0.6)) this.blip(360, 0.12, 'sawtooth', 0.10, 620); },
  toss:    function () { if (!this.play('toss', 1, 0.8)) this.blip(200, 0.10, 'square',   0.16, 120); },
  paper:   function () { if (!this.play('fanfare', 1, 0.9)) this.combo(4); },
  arrive:  function () { if (!this.play('arrive', 1, 0.4)) this.blip(880, 0.10, 'sine', 0.10, 1170); },
  start:   function () { if (!this.play('fanfare', 1, 0.85)) { var s = this, notes = [523, 659, 784, 1046];
                         notes.forEach(function (f, i) { setTimeout(function () { s.blip(f, 0.12, 'triangle', 0.26); }, i * 90); }); } },

  // tiny / melodic cues stay on the synth (cheap, frequent, or sequenced)
  tick:    function () { this.blip(880, 0.05, 'square', 0.18); },
  gameover: function () { var s = this, notes = [784, 659, 523, 392];
                          notes.forEach(function (f, i) { setTimeout(function () { s.blip(f, 0.18, 'triangle', 0.26); }, i * 140); }); }
};
